import type { Metadata } from "next";
import localFont from "next/font/local";
import { Gruppo } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const gruppo = Gruppo({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-gruppo",
  weight: "400",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Victoria Raya",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gruppo.className} bg-[#b291a4] dark:bg-[#4a3f47]`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
